### PR TITLE
All render tasks have a width and height

### PR DESCRIPTION
**Pull request by tntmeijs**
**Description**
Render tasks now have a width and height optional parameter.

**Issues**
Not applicable.

**Possible conflicts**
Not applicable.

### CODE REVIEW

**Comment by tntmeijs** [comment]
> Looks good, though I haven't tested with width/height of std::nullopt. Has this been tested?

I did test it. But it'll be best if somebody else could try it as well.

**Comment by VZout** [comment]
Forgot to review this. Could you merge this please?

**Comment by tntmeijs** [comment]
@Nielsbishere suggested a "fix" to hide the window. I'll keep this PR open until we have made a decision regarding the window.

**Comment by VZout** [comment]
Closing for now. Seems state.

**Pull request closed without merging**
